### ISSUE TITLE
Redundancy?

### ISSUE THREAD

**Issue by blttkgl** [ZmengXu/minMaxLength#1]
Hey, 

Out of curiosity, how is this function object differ from the [fieldMinMax function object of OpenFOAM](https://github.com/OpenFOAM/OpenFOAM-dev/blob/2caad45a9b5ec6db05687aefcafe275877edc776/src/functionObjects/field/fieldMinMax/fieldMinMax.H), which already has a location flag that stores the location of the minimum or maximum of a field?

From the header:
```

Usage
    \table
        Property     | Description             | Required    | Default value
        type         | type name: fieldMinMax  | yes         |
        log          | write min/max data to standard output | no | no
        location     | write location of the min/max value | no | yes
        mode         | calculation mode: magnitude or component | no | magnitude
    \endtable
```

Best,

Bulut

**Comment by ZmengXu** [comment]
Hi Bulut,

Thank you for your question.
This is a function object which can return the maximum and minimum length of a field reaching a criterion value. For example, you can use it to get the temporal evolution of the lift-off length, e.g., setting the fieldName as OH, criterion as a mass fraction of 0.001. You can also use it to get the vapor penetration length, e.g., setting the fieldName as Z, criterion as a Z = 0.001.
I wrote it for temporary usage. The header and the detailed `README.md` file are missing now. I may make it better later if someone thinks it is useful.

Best Regards,
Shijie

**Comment by blttkgl** [comment]
Dear Shijie,

That makes perfect sense. I bet one can achieve the same functionality by combining two function objects that openfoam already has, such as fieldMinMax and fieldExtent, but it is nice to have a utility already doing this job. I'm sure my colleague @mahgadalla would also be interested with your utility.

Keep up the good work!

Bulut

**Comment by mahgadalla** [comment]
Thank you Shijie @ZmengXu  and Bulut @blttkgl for the fruitful discussion. Yes, the function object is pretty handy and could be quite useful. I used to create my own postProcessing utilities for FLOL and penetration lengths but perhaps starting from this functionObj is better. Thanks for the efforts!!!

Mahmoud

**Comment by ZmengXu** [comment]
> Dear Shijie,
> 
> That makes perfect sense. I bet one can achieve the same functionality by combining two function objects that openfoam already has, such as fieldMinMax and fieldExtent, but it is nice to have a utility already doing this job. I'm sure my colleague @mahgadalla would also be interested with your utility.
> 
> Keep up the good work!
> 
> Bulut

Dear Bulut,
It is good to know that you and your colleague are interested in it. I have updated this functionObject to improve the log file writing. I think you are right, fieldMinMax and fieldExtent could also work. As I have written it, making it available should be good for someone.
Best Regards,
Shijie

**Comment by ZmengXu** [comment]
> Thank you Shijie @ZmengXu and Bulut @blttkgl for the fruitful discussion. Yes, the function object is pretty handy and could be quite useful. I used to create my own postProcessing utilities for FLOL and penetration lengths but perhaps starting from this functionObj is better. Thanks for the efforts!!!
> 
> Mahmoud

Dear Mahmoud,
Thank you for your comment. I have updated this functionObject to improve the log file writing. Feel free to use it and pls let me know if you have any issues when you use it.
Best Regards,
Shijie
